# Generated by Django 3.2.5 on 2021-07-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('standard', models.IntegerField()),
                ('roll_no', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=30)),
                ('new_student', models.BooleanField()),
            ],
        ),
    ]
