# Generated by Django 3.2.5 on 2021-07-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('standard', models.IntegerField()),
                ('roll_no', models.AutoField(primary_key=True, serialize=False)),
                ('male', models.CharField(max_length=1)),
                ('city', models.CharField(max_length=30)),
                ('new_student', models.BooleanField()),
            ],
        ),
    ]
