# Generated by Django 3.2.5 on 2021-07-27 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='new_student',
        ),
    ]
